// ═══════════════ 词汇与构词点读数据 ═══════════════
// 5 大章节：前缀 / 后缀 / 词根 / 主题词汇 / 功能词
// 由 LexiconTab（src/components/russian-toolkit.tsx）渲染为点读卡片：
//   - 点击卡片调用 playRu(ru) 朗读（TTS 层会剥离 U+0301 重音标记）
//   - stressNodes(ru) 把 U+0301 转成重读元音高亮 span
// 重音标记规则：在重读元音后紧接 U+0301（组合锐音符），如 полиме́р
// 单音节词不标重音；裸词缀/词根不标重音，只在 examples 中标

export type LexEntry = {
  ru: string
  zh: string
  en: string
  examples?: Array<{ ru: string; zh: string; en: string }>
  note?: string
}

export type LexGroup = {
  id: string
  title: { zh: string; en: string; ru: string }
  items: LexEntry[]
}

export type LexSectionId = 'prefix' | 'suffix' | 'root' | 'theme' | 'function'

export type LexSection = {
  id: LexSectionId
  title: { zh: string; en: string; ru: string }
  groups: LexGroup[]
}

export const LEX_SECTIONS: LexSection[] = [
  // ───────── 前缀 ─────────
  {
    id: 'prefix',
    title: { zh: '前缀与构词前部', en: 'Prefixes', ru: 'Приставки' },
    groups: [
      {
        id: 'motion',
        title: { zh: '方位·运动前缀', en: 'Directional prefixes', ru: 'Приставки направления движения' },
        items: [
          { ru: 'при-', zh: '来到、靠近', en: 'arrival, approach', examples: [{ ru: 'прийти́', zh: '来到', en: 'to come' }, { ru: 'прие́хать', zh: '乘车到达', en: 'to arrive (by transport)' }] },
          { ru: 'вы-', zh: '向外、离开', en: 'outward, out of', examples: [{ ru: 'вы́йти', zh: '走出去', en: 'to go out' }, { ru: 'вы́бежать', zh: '跑出去', en: 'to run out' }] },
          { ru: 'у-', zh: '离去、远离', en: 'leaving, away', examples: [{ ru: 'уйти́', zh: '离开', en: 'to leave' }, { ru: 'уе́хать', zh: '乘车离开', en: 'to leave by transport' }] },
          { ru: 'от-/ото-', zh: '脱离、离开', en: 'off, away from', examples: [{ ru: 'отойти́', zh: '走开', en: 'to step away' }, { ru: 'отбежа́ть', zh: '跑开', en: 'to run away' }] },
          { ru: 'до-', zh: '到达、抵达', en: 'reaching, up to', examples: [{ ru: 'дойти́', zh: '走到', en: 'to reach on foot' }, { ru: 'дое́хать', zh: '乘车到达', en: 'to reach by transport' }] },
          { ru: 'под-/подо-', zh: '靠近、自下', en: 'approach, from below', examples: [{ ru: 'подойти́', zh: '走近', en: 'to approach' }, { ru: 'подплы́ть', zh: '游近', en: 'to swim up to' }] },
          { ru: 'пере-', zh: '跨越、转移', en: 'across, transfer', examples: [{ ru: 'перейти́', zh: '穿过', en: 'to cross' }, { ru: 'перее́хать', zh: '搬迁', en: 'to move house' }] },
          { ru: 'об-/обо-', zh: '环绕、绕过', en: 'around, bypass', examples: [{ ru: 'обойти́', zh: '绕行', en: 'to go around' }, { ru: 'объе́хать', zh: '驾车绕过', en: 'to drive around' }] },
        ],
      },
      {
        id: 'spatial',
        title: { zh: '空间·位置前缀', en: 'Spatial prefixes', ru: 'Приставки положения в пространстве' },
        items: [
          { ru: 'на-', zh: '接触、附着于上', en: 'on, onto', examples: [{ ru: 'напи́сать', zh: '写下', en: 'to write down' }, { ru: 'положи́ть', zh: '放下', en: 'to put down' }] },
          { ru: 'за-', zh: '处于其后、标记', en: 'behind, mark', examples: [{ ru: 'запи́сать', zh: '记录下', en: 'to note down' }, { ru: 'заяви́ть', zh: '声明', en: 'to declare' }] },
          { ru: 'над-/надо-', zh: '在上方', en: 'above, over', examples: [{ ru: 'надпи́сать', zh: '题写于上', en: 'to inscribe above' }, { ru: 'надстро́ить', zh: '加建', en: 'to build on top' }] },
          { ru: 'под-/подо-', zh: '在下方', en: 'under, beneath', examples: [{ ru: 'подпи́сать', zh: '签名', en: 'to sign' }, { ru: 'подкра́сить', zh: '涂底色', en: 'to undercoat' }] },
          { ru: 'между-', zh: '在之间', en: 'between', examples: [{ ru: 'междуго́род', zh: '城际', en: 'intercity' }, { ru: 'междунаро́дный', zh: '国际的', en: 'international' }] },
          { ru: 'вне-', zh: '在之外', en: 'outside of', examples: [{ ru: 'внеклас́сный', zh: '课外的', en: 'extracurricular' }, { ru: 'внепла́новый', zh: '计划外的', en: 'unscheduled' }] },
          { ru: 'при-', zh: '附加、毗邻', en: 'attached, near', examples: [{ ru: 'пришко́льный', zh: '附属于学校的', en: 'school-affiliated' }, { ru: 'примо́рье', zh: '沿海地区', en: 'coastal area' }] },
        ],
      },
      {
        id: 'degree',
        title: { zh: '程度·大小前缀', en: 'Degree & size prefixes', ru: 'Приставки степени и размера' },
        items: [
          { ru: 'пере-', zh: '过度、超出', en: 'over-, excessively', examples: [{ ru: 'перее́сть', zh: '吃得过多', en: 'to overeat' }, { ru: 'переоцени́ть', zh: '高估', en: 'to overestimate' }] },
          { ru: 'недо-', zh: '不足', en: 'under-, insufficiently', examples: [{ ru: 'недооцени́ть', zh: '低估', en: 'to underestimate' }, { ru: 'недоста́точный', zh: '不充分的', en: 'insufficient' }] },
          { ru: 'пре-', zh: '极度、转变', en: 'highly, transformation', examples: [{ ru: 'преувели́чить', zh: '夸大', en: 'to exaggerate' }, { ru: 'пренебре́чь', zh: '忽视', en: 'to neglect' }] },
          { ru: 'сверх-', zh: '超出、超级', en: 'super-, beyond', examples: [{ ru: 'сверхпроводи́мость', zh: '超导性', en: 'superconductivity' }, { ru: 'свы́ше', zh: '以上', en: 'over, above' }] },
          { ru: 'архи-', zh: '极度、首要', en: 'arch-, chief', examples: [{ ru: 'архи́епископ', zh: '大主教', en: 'archbishop' }, { ru: 'архивы́жный', zh: '极重要的', en: 'arch-vital' }] },
          { ru: 'на-', zh: '充满、达极限', en: 'to the full', examples: [{ ru: 'насы́пать', zh: '盛满', en: 'to heap' }, { ru: 'наезди́ть', zh: '多次往返', en: 'to travel often' }] },
        ],
      },
      {
        id: 'negation',
        title: { zh: '否定·反对前缀', en: 'Negation prefixes', ru: 'Приставки отрицания' },
        items: [
          { ru: 'не-', zh: '不、非', en: 'un-, non-', examples: [{ ru: 'невыго́дный', zh: '不利的', en: 'unprofitable' }, { ru: 'недово́лен', zh: '不满的', en: 'dissatisfied' }] },
          { ru: 'без-/бес-', zh: '无、缺', en: 'without, -less', examples: [{ ru: 'бессмы́сленный', zh: '无意义的', en: 'meaningless' }, { ru: 'беззаве́тный', zh: '无私的', en: 'selfless' }] },
          { ru: 'анти-', zh: '反、抗', en: 'anti-', examples: [{ ru: 'антибактериа́льный', zh: '抗菌的', en: 'antibacterial' }, { ru: 'антиморо́зный', zh: '防冻的', en: 'antifreeze' }] },
          { ru: 'противо-', zh: '反对、防止', en: 'counter-, anti-', examples: [{ ru: 'противога́з', zh: '防毒面具', en: 'gas mask' }, { ru: 'противосто́ять', zh: '对抗', en: 'to withstand' }] },
          { ru: 'а-', zh: '非、不', en: 'a-, non-', examples: [{ ru: 'асимметри́я', zh: '不对称', en: 'asymmetry' }, { ru: 'алоги́чный', zh: '不合逻辑的', en: 'illogical' }] },
          { ru: 'дис-/дез-', zh: '紊乱、剥离', en: 'dis-, de-', examples: [{ ru: 'дисгармо́ния', zh: '不和谐', en: 'disharmony' }, { ru: 'дезинфе́кция', zh: '消毒', en: 'disinfection' }] },
        ],
      },
      {
        id: 'repetition',
        title: { zh: '重复·再前缀', en: 'Repetition prefixes', ru: 'Приставки повторного действия' },
        items: [
          { ru: 'пере-', zh: '重新、再', en: 're-, again', examples: [{ ru: 'перепи́сать', zh: '重写', en: 'to rewrite' }, { ru: 'перестро́ить', zh: '重建', en: 'to rebuild' }] },
          { ru: 'воз-/вос-/возо-', zh: '恢复、使再', en: 're-, restore', examples: [{ ru: 'возроди́ть', zh: '复兴', en: 'to revive' }, { ru: 'восстанови́ть', zh: '恢复', en: 'to restore' }] },
          { ru: 'до-', zh: '补充完成', en: 'finish off', examples: [{ ru: 'допи́сать', zh: '写完', en: 'to finish writing' }, { ru: 'достро́ить', zh: '续建完成', en: 'to finish building' }] },
          { ru: 'на-', zh: '积累、反复', en: 'accumulate', examples: [{ ru: 'нагова́ривать', zh: '多次说', en: 'to talk much' }, { ru: 'наезжи́вать', zh: '频繁往来', en: 'to frequent' }] },
          { ru: 'про-', zh: '贯穿、彻底', en: 'through, thoroughly', examples: [{ ru: 'прочита́ть', zh: '通读', en: 'to read through' }, { ru: 'прорабо́тать', zh: '深入研究', en: 'to work through' }] },
        ],
      },
      {
        id: 'time',
        title: { zh: '时间·顺序前缀', en: 'Time & order prefixes', ru: 'Приставки времени и порядка' },
        items: [
          { ru: 'пред-', zh: '在之前', en: 'before, pre-', examples: [{ ru: 'предви́деть', zh: '预见', en: 'to foresee' }, { ru: 'предысто́рия', zh: '前史', en: 'prehistory' }] },
          { ru: 'после-', zh: '在之后', en: 'after, post-', examples: [{ ru: 'после́дствие', zh: '后果', en: 'consequence' }, { ru: 'после́завтра', zh: '后天', en: 'the day after tomorrow' }] },
          { ru: 'за-', zh: '开始、之后', en: 'begin, after', examples: [{ ru: 'заговори́ть', zh: '开始说起话', en: 'to start talking' }, { ru: 'заста́вить', zh: '迫使', en: 'to compel' }] },
          { ru: 'до-', zh: '直至、之前', en: 'until, prior', examples: [{ ru: 'дочита́ть', zh: '读到底', en: 'to read to end' }, { ru: 'доистори́ческий', zh: '史前的', en: 'pre-historic' }] },
          { ru: 'пере-', zh: '时段跨越', en: 'across a period', examples: [{ ru: 'перено́чевать', zh: '过夜', en: 'to overnight' }, { ru: 'перезимова́ть', zh: '越冬', en: 'to winter over' }] },
        ],
      },
      {
        id: 'relation',
        title: { zh: '联合·关系前缀', en: 'Association prefixes', ru: 'Приставки связи и отношения' },
        items: [
          { ru: 'со-/с-', zh: '共同、联合', en: 'joint, together', examples: [{ ru: 'сотру́дник', zh: '同事', en: 'colleague' }, { ru: 'соревнова́ться', zh: '竞赛', en: 'to compete' }] },
          { ru: 'об-/обо-', zh: '相互、使成', en: 'mutual, make', examples: [{ ru: 'обменя́ться', zh: '互相交换', en: 'to exchange' }, { ru: 'облегчи́ть', zh: '减轻', en: 'to ease' }] },
          { ru: 'взаимо-', zh: '相互', en: 'inter-, mutual', examples: [{ ru: 'взаимоде́йствие', zh: '相互作用', en: 'interaction' }, { ru: 'взаимопонима́ние', zh: '相互理解', en: 'mutual understanding' }] },
          { ru: 'между-', zh: '之间', en: 'inter-', examples: [{ ru: 'междунаро́дный', zh: '国际的', en: 'international' }, { ru: 'межотрасле́вой', zh: '跨行业的', en: 'intersectoral' }] },
          { ru: 'под-', zh: '从属、次要', en: 'sub-', examples: [{ ru: 'подгру́ппа', zh: '子群', en: 'subgroup' }, { ru: 'подразделе́ние', zh: '下属单位', en: 'subdivision' }] },
        ],
      },
    ],
  },

  // ───────── 后缀 ─────────
  {
    id: 'suffix',
    title: { zh: '后缀与构词后部', en: 'Suffixes', ru: 'Суффиксы' },
    groups: [
      {
        id: 'noun-person',
        title: { zh: '名词·人物后缀', en: 'Person noun suffixes', ru: 'Суффиксы лиц' },
        items: [
          { ru: '-тель', zh: '执行者、做…的人', en: 'doer, agent', examples: [{ ru: 'учи́тель', zh: '教师', en: 'teacher' }, { ru: 'писа́тель', zh: '作家', en: 'writer' }] },
          { ru: '-ник', zh: '从事…的人或器物', en: 'doer, implement', examples: [{ ru: 'учени́к', zh: '学生', en: 'pupil' }, { ru: 'холоди́льник', zh: '冰箱', en: 'fridge' }] },
          { ru: '-ист', zh: '从事…者', en: '-ist, practitioner', examples: [{ ru: 'такси́ст', zh: '出租车司机', en: 'taxi driver' }, { ru: 'гитари́ст', zh: '吉他手', en: 'guitarist' }] },
          { ru: '-ик', zh: '从事…者、专业人员', en: 'specialist', examples: [{ ru: 'ме́ханик', zh: '机械师', en: 'mechanic' }, { ru: 'программи́ст', zh: '程序员', en: 'programmer' }] },
          { ru: '-ец', zh: '具有某属性的人', en: 'person of', examples: [{ ru: 'иностра́нец', zh: '外国人', en: 'foreigner' }, { ru: 'горе́ц', zh: '登山者', en: 'mountaineer' }] },
          { ru: '-ша', zh: '女性职业者', en: 'female professional', examples: [{ ru: 'касси́рша', zh: '女收银员', en: 'female cashier' }, { ru: 'библиоте́карша', zh: '女图书管理员', en: 'female librarian' }] },
          { ru: '-чик/-щик', zh: '从事…者', en: 'doer (profession)', examples: [{ ru: 'перево́дчик', zh: '翻译', en: 'translator' }, { ru: 'сва́рщик', zh: '焊工', en: 'welder' }] },
          { ru: '-ак/-як', zh: '具有特征者', en: 'person with trait', examples: [{ ru: 'горня́к', zh: '矿工', en: 'miner' }, { ru: 'бедня́к', zh: '穷人', en: 'poor person' }] },
        ],
      },
      {
        id: 'noun-abstract',
        title: { zh: '名词·抽象概念后缀', en: 'Abstract noun suffixes', ru: 'Суффиксы отвлечённых понятий' },
        items: [
          { ru: '-ость', zh: '性质、状态', en: 'quality, -ness', examples: [{ ru: 'но́вость', zh: '新闻', en: 'novelty' }, { ru: 'ра́дость', zh: '喜悦', en: 'joy' }] },
          { ru: '-ение', zh: '动作、结果', en: 'action, result', examples: [{ ru: 'реше́ние', zh: '解决/决定', en: 'solution' }, { ru: 'создание', zh: '创建', en: 'creation' }] },
          { ru: '-ание', zh: '动作过程', en: 'action process', examples: [{ ru: 'писа́ние', zh: '书写', en: 'writing' }, { ru: 'чта́ние', zh: '阅读', en: 'reading' }] },
          { ru: '-ство', zh: '状态、集体', en: 'state, collective', examples: [{ ru: 'госуда́рство', zh: '国家', en: 'state' }, { ru: 'о́бщество', zh: '社会', en: 'society' }] },
          { ru: '-ие', zh: '抽象状态', en: 'abstract state', examples: [{ ru: 'собра́ние', zh: '集会', en: 'assembly' }, { ru: 'соче́тание', zh: '结合', en: 'combination' }] },
          { ru: '-изм', zh: '主义、学说', en: '-ism, doctrine', examples: [{ ru: 'капитали́зм', zh: '资本主义', en: 'capitalism' }, { ru: 'оптимизм', zh: '乐观主义', en: 'optimism' }] },
          { ru: '-ота', zh: '性质、状态', en: 'quality', examples: [{ ru: 'красота́', zh: '美', en: 'beauty' }, { ru: 'пустота́', zh: '空', en: 'emptiness' }] },
        ],
      },
      {
        id: 'noun-place',
        title: { zh: '名词·处所容器后缀', en: 'Place / container suffixes', ru: 'Суффиксы места и вместилища' },
        items: [
          { ru: '-льня', zh: '处所', en: 'place', examples: [{ ru: 'чита́льня', zh: '阅览室', en: 'reading room' }, { ru: 'ку́хня', zh: '厨房', en: 'kitchen' }] },
          { ru: '-лка', zh: '处所、器物', en: 'place, device', examples: [{ ru: 'раздева́лка', zh: '更衣室', en: 'cloakroom' }, { ru: 'гото́вка', zh: '准备处', en: 'prep area' }] },
          { ru: '-ница', zh: '容器', en: 'container', examples: [{ ru: 'саха́рница', zh: '糖罐', en: 'sugar bowl' }, { ru: 'мы́льница', zh: '皂盒', en: 'soap dish' }] },
          { ru: '-ище', zh: '大处所', en: 'large place', examples: [{ ru: 'кладби́ще', zh: '墓地', en: 'cemetery' }, { ru: 'учи́лище', zh: '学校', en: 'school' }] },
          { ru: '-ня', zh: '处所', en: 'place', examples: [{ ru: 'поко́йня', zh: '停尸间', en: 'morgue' }, { ru: 'ба́ня', zh: '澡堂', en: 'bathhouse' }] },
          { ru: '-арий', zh: '专用场所', en: 'facility', examples: [{ ru: 'планета́рий', zh: '天文馆', en: 'planetarium' }, { ru: 'медсанчасть', zh: '医务所', en: 'clinic' }] },
        ],
      },
      {
        id: 'noun-diminutive',
        title: { zh: '名词·指小表爱后缀', en: 'Diminutive suffixes', ru: 'Уменьшительно-ласкательные суффиксы' },
        items: [
          { ru: '-ик', zh: '小、亲昵', en: 'small, endearing', examples: [{ ru: 'доми́к', zh: '小房子', en: 'little house' }, { ru: 'дождик', zh: '小雨', en: 'light rain' }] },
          { ru: '-ек', zh: '小', en: 'small', examples: [{ ru: 'сыно́к', zh: '小儿子', en: 'little son' }, { ru: 'кусочек', zh: '小块', en: 'small piece' }] },
          { ru: '-к(а)', zh: '小、亲昵', en: 'small, dear', examples: [{ ru: 'ру́чка', zh: '小手/笔', en: 'pen' }, { ru: 'де́вочка', zh: '小女孩', en: 'little girl' }] },
          { ru: '-еньк(а)', zh: '娇小可爱', en: 'cute small', examples: [{ ru: 'ма́ленький', zh: '小小的', en: 'little' }, { ru: 'ру́ченька', zh: '小手儿', en: 'tiny hand' }] },
          { ru: '-ушк(а)/-юшк(а)', zh: '亲昵', en: 'endearing', examples: [{ ru: 'голо́сушка', zh: '小嗓音', en: 'dear voice' }, { ru: 'до́мик-домушко', zh: '小屋', en: 'little house' }] },
          { ru: '-ыш(ек)', zh: '小', en: 'small', examples: [{ ru: 'пёрышко', zh: '小羽毛', en: 'little feather' }, { ru: 'со́лнышко', zh: '小太阳', en: 'little sun' }] },
        ],
      },
      {
        id: 'noun-augmentive',
        title: { zh: '名词·增大表贬后缀', en: 'Augmentative / pejorative', ru: 'Увеличительные и пренебрежительные суффиксы' },
        items: [
          { ru: '-ище', zh: '巨大', en: 'big, huge', examples: [{ ru: 'доми́ще', zh: '大房子', en: 'huge house' }, { ru: 'бороди́ще', zh: '大胡子', en: 'huge beard' }] },
          { ru: '-ища', zh: '极度', en: 'extreme', examples: [{ ru: 'дура́чи́ща', zh: '大傻瓜', en: 'big fool' }, { ru: 'ручи́ща', zh: '粗大手臂', en: 'huge hand' }] },
          { ru: '-ина', zh: '大、整块', en: 'large, whole', examples: [{ ru: 'доми́на', zh: '大房子', en: 'big house' }, { ru: 'мя́сина', zh: '大块肉', en: 'slab of meat' }] },
          { ru: '-ёжа', zh: '贬义', en: 'pejorative', examples: [{ ru: 'бума́жка', zh: '破纸片', en: 'scrap of paper' }, { ru: 'кни́жка', zh: '小册子', en: 'booklet' }] },
          { ru: '-уга', zh: '贬义', en: 'pejorative', examples: [{ ru: 'здоровя́га', zh: '壮汉', en: 'big guy' }, { ru: 'бедня́га', zh: '可怜虫', en: 'poor wretch' }] },
        ],
      },
      {
        id: 'adjective',
        title: { zh: '形容词后缀', en: 'Adjective suffixes', ru: 'Суффиксы прилагательных' },
        items: [
          { ru: '-н(ый)', zh: '具有…的', en: '-al, having', examples: [{ ru: 'но́вый', zh: '新的', en: 'new' }, { ru: 'ле́тний', zh: '夏天的', en: 'summer' }] },
          { ru: '-ск(ий)', zh: '属于…的', en: 'belonging to', examples: [{ ru: 'москвко́вский', zh: '莫斯科的', en: 'Moscow' }, { ru: 'горо́дской', zh: '城市的', en: 'urban' }] },
          { ru: '-ов(ый)', zh: '由…构成', en: 'made of', examples: [{ ru: 'дубо́вый', zh: '橡木的', en: 'oak' }, { ru: 'светово́й', zh: '光的', en: 'light' }] },
          { ru: '-ив(ый)', zh: '具有…特质', en: 'having quality', examples: [{ ru: 'ле́ни́вый', zh: '懒的', en: 'lazy' }, { ru: 'краси́вый', zh: '美丽的', en: 'beautiful' }] },
          { ru: '-лив(ый)', zh: '具有…倾向', en: 'prone to', examples: [{ ru: 'дожли́вый', zh: '多雨的', en: 'rainy' }, { ru: 'болтли́вый', zh: '健谈的', en: 'talkative' }] },
          { ru: '-ист(ый)', zh: '富含…的', en: 'rich in', examples: [{ ru: 'гли́нистый', zh: '黏土质的', en: 'clayey' }, { ru: 'золоти́стый', zh: '金黄色的', en: 'golden' }] },
          { ru: '-к(ий)', zh: '具有…性质', en: 'having quality', examples: [{ ru: 'гро́мкий', zh: '大声的', en: 'loud' }, { ru: 'ре́зкий', zh: '尖锐的', en: 'sharp' }] },
        ],
      },
      {
        id: 'adverb',
        title: { zh: '副词与不定代词后缀', en: 'Adverb & indefinite suffixes', ru: 'Суффиксы наречий и неопределённых слов' },
        items: [
          { ru: '-о', zh: '构成副词', en: 'forms adverb', examples: [{ ru: 'быстро', zh: '快', en: 'quickly' }, { ru: 'краси́во', zh: '美地', en: 'beautifully' }] },
          { ru: '-е', zh: '构成副词', en: 'forms adverb', examples: [{ ru: 'певу́че', zh: '如歌地', en: 'melodiously' }, { ru: 'подобаю́ще', zh: '得体地', en: 'fittingly' }] },
          { ru: '-ски', zh: '方式副词', en: 'manner adverb', examples: [{ ru: 'по-ру́сски', zh: '按俄式', en: 'Russian-style' }, { ru: 'по-дру́жески', zh: '友好地', en: 'friendly' }] },
          { ru: '-ому', zh: '方式副词', en: 'manner adverb', examples: [{ ru: 'по-но́вому', zh: '按新方式', en: 'in a new way' }, { ru: 'по-на́шему', zh: '按我们的', en: 'our way' }] },
          { ru: '-нибудь', zh: '不定', en: 'indefinite', examples: [{ ru: 'что́-нибудь', zh: '随便什么', en: 'anything' }, { ru: 'где́-нибудь', zh: '随便哪里', en: 'somewhere or other' }] },
          { ru: '-либо', zh: '不定', en: 'indefinite', examples: [{ ru: 'кто́-либо', zh: '任何一个', en: 'anyone' }, { ru: 'когда́-либо', zh: '任何时候', en: 'any time' }] },
        ],
      },
      {
        id: 'verb-aspect',
        title: { zh: '动词体与反身后缀', en: 'Verb aspect & reflexive suffixes', ru: 'Суффиксы вида и возвратности' },
        items: [
          { ru: '-ну(ть)', zh: '瞬间、一次动作', en: 'momentary action', examples: [{ ru: 'пры́гнуть', zh: '跳一下', en: 'to jump once' }, { ru: 'кри́кнуть', zh: '喊一声', en: 'to shout once' }] },
          { ru: '-ива/-ыва', zh: '多次未完成体', en: 'iterative imperfective', examples: [{ ru: 'расска́зывать', zh: '讲述', en: 'to tell' }, { ru: 'пока́зывать', zh: '展示', en: 'to show' }] },
          { ru: '-ва', zh: '使成动词', en: 'causative', examples: [{ ru: 'дава́ть', zh: '给予', en: 'to give' }, { ru: 'создава́ть', zh: '创建', en: 'to create' }] },
          { ru: '-ся', zh: '反身、被动', en: 'reflexive, passive', examples: [{ ru: 'умыва́ться', zh: '洗漱', en: 'to wash oneself' }, { ru: 'стро́иться', zh: '被建造', en: 'to be built' }] },
          { ru: '-сь', zh: '反身（元音后）', en: 'reflexive (after vowel)', examples: [{ ru: 'одева́юсь', zh: '我穿衣', en: 'I dress' }, { ru: 'нра́вится', zh: '讨人喜欢', en: 'is pleasing' }] },
          { ru: '-е(ть)', zh: '成为', en: 'to become', examples: [{ ru: 'старе́ть', zh: '变老', en: 'to grow old' }, { ru: 'красне́ть', zh: '变红', en: 'to turn red' }] },
          { ru: '-и(ть)', zh: '使成', en: 'to make', examples: [{ ru: 'бели́ть', zh: '涂白', en: 'to whiten' }, { ru: 'суши́ть', zh: '弄干', en: 'to dry' }] },
        ],
      },
    ],
  },

  // ───────── 词根 ─────────
  {
    id: 'root',
    title: { zh: '词根', en: 'Roots', ru: 'Корни' },
    groups: [
      {
        id: 'person-life',
        title: { zh: '人称与生命词根', en: 'Person & life roots', ru: 'Корни лиц и жизни' },
        items: [
          { ru: '-род-', zh: '出生、族类', en: 'birth, kin', examples: [{ ru: 'роди́тели', zh: '父母', en: 'parents' }, { ru: 'наро́д', zh: '人民', en: 'people' }] },
          { ru: '-жизн-', zh: '生命', en: 'life', examples: [{ ru: 'жизнь', zh: '生命', en: 'life' }, { ru: 'жи́зненный', zh: '生命的', en: 'vital' }] },
          { ru: '-мёртв-/-мир-', zh: '死亡', en: 'death, dead', examples: [{ ru: 'мёртвый', zh: '死的', en: 'dead' }, { ru: 'умира́ть', zh: '死去', en: 'to die' }] },
          { ru: '-мат-', zh: '母亲', en: 'mother', examples: [{ ru: 'ма́ма', zh: '妈妈', en: 'mom' }, { ru: 'ма́терний', zh: '母亲的', en: 'maternal' }] },
          { ru: '-отч-', zh: '父亲', en: 'father', examples: [{ ru: 'оте́ц', zh: '父亲', en: 'father' }, { ru: 'о́тчество', zh: '父名', en: 'patronymic' }] },
          { ru: '-друж-', zh: '朋友', en: 'friend', examples: [{ ru: 'друг', zh: '朋友', en: 'friend' }, { ru: 'дружба', zh: '友谊', en: 'friendship' }] },
        ],
      },
      {
        id: 'action',
        title: { zh: '动作词根', en: 'Action roots', ru: 'Корни действий' },
        items: [
          { ru: '-вод-', zh: '引导、带领', en: 'to lead', examples: [{ ru: 'води́ть', zh: '带领', en: 'to lead' }, { ru: 'води́тель', zh: '司机', en: 'driver' }] },
          { ru: '-ход-', zh: '走、行', en: 'to go, walk', examples: [{ ru: 'выход', zh: '出口', en: 'exit' }, { ru: 'прихо́д', zh: '到来', en: 'arrival' }] },
          { ru: '-пис-', zh: '写', en: 'to write', examples: [{ ru: 'писа́ть', zh: '写', en: 'to write' }, { ru: 'подпи́сь', zh: '签名', en: 'signature' }] },
          { ru: '-чит-', zh: '读', en: 'to read', examples: [{ ru: 'чита́ть', zh: '读', en: 'to read' }, { ru: 'чита́тель', zh: '读者', en: 'reader' }] },
          { ru: '-говор-', zh: '说、讲话', en: 'to speak', examples: [{ ru: 'говори́ть', zh: '说', en: 'to speak' }, { ru: 'разгово́р', zh: '谈话', en: 'conversation' }] },
          { ru: '-держ-', zh: '持、握', en: 'to hold', examples: [{ ru: 'держа́ть', zh: '握住', en: 'to hold' }, { ru: 'подде́ржка', zh: '支持', en: 'support' }] },
          { ru: '-став-', zh: '放置、立', en: 'to put, stand', examples: [{ ru: 'ста́вить', zh: '放置', en: 'to put' }, { ru: 'остано́вка', zh: '停车站', en: 'stop' }] },
          { ru: '-бег-', zh: '跑', en: 'to run', examples: [{ ru: 'бежа́ть', zh: '跑', en: 'to run' }, { ru: 'бег', zh: '跑步', en: 'running' }] },
        ],
      },
      {
        id: 'nature',
        title: { zh: '自然与物质词根', en: 'Nature & matter roots', ru: 'Корни природы и вещества' },
        items: [
          { ru: '-вод-(水)', zh: '水', en: 'water', examples: [{ ru: 'вода́', zh: '水', en: 'water' }, { ru: 'подводный', zh: '水下的', en: 'underwater' }] },
          { ru: '-свет-', zh: '光', en: 'light', examples: [{ ru: 'свет', zh: '光', en: 'light' }, { ru: 'све́тлый', zh: '明亮的', en: 'bright' }] },
          { ru: '-цвет-', zh: '颜色', en: 'color', examples: [{ ru: 'цвет', zh: '颜色', en: 'color' }, { ru: 'цветно́й', zh: '彩色的', en: 'colored' }] },
          { ru: '-звук-', zh: '声音', en: 'sound', examples: [{ ru: 'звук', zh: '声音', en: 'sound' }, { ru: 'звуча́ть', zh: '响起', en: 'to sound' }] },
          { ru: '-земл-', zh: '土地', en: 'earth', examples: [{ ru: 'земля́', zh: '土地', en: 'earth' }, { ru: 'земно́й', zh: '地球的', en: 'earthly' }] },
          { ru: '-лес-', zh: '森林', en: 'forest', examples: [{ ru: 'лес', zh: '森林', en: 'forest' }, { ru: 'ле́сной', zh: '森林的', en: 'forest' }] },
        ],
      },
      {
        id: 'object',
        title: { zh: '物品与器物词根', en: 'Object roots', ru: 'Корни предметов' },
        items: [
          { ru: '-рук-', zh: '手', en: 'hand', examples: [{ ru: 'рука́', zh: '手', en: 'hand' }, { ru: 'ручно́й', zh: '手动的', en: 'manual' }] },
          { ru: '-ног-', zh: '脚、腿', en: 'foot, leg', examples: [{ ru: 'нога́', zh: '腿', en: 'leg' }, { ru: 'ножно́й', zh: '腿的', en: 'leg-' }] },
          { ru: '-глаз-', zh: '眼', en: 'eye', examples: [{ ru: 'глаз', zh: '眼睛', en: 'eye' }, { ru: 'глазно́й', zh: '眼的', en: 'eye-' }] },
          { ru: '-слов-', zh: '词', en: 'word', examples: [{ ru: 'сло́во', zh: '词', en: 'word' }, { ru: 'сло́варь', zh: '词典', en: 'dictionary' }] },
          { ru: '-дом-', zh: '房屋', en: 'house', examples: [{ ru: 'дом', zh: '房子', en: 'house' }, { ru: 'домашний', zh: '家里的', en: 'domestic' }] },
          { ru: '-стол-', zh: '桌子', en: 'table', examples: [{ ru: 'стол', zh: '桌子', en: 'table' }, { ru: 'столо́вая', zh: '餐厅', en: 'dining room' }] },
        ],
      },
      {
        id: 'state-quality',
        title: { zh: '状态与性质词根', en: 'State & quality roots', ru: 'Корни состояния и качества' },
        items: [
          { ru: '-зн-', zh: '知道', en: 'to know', examples: [{ ru: 'зна́ть', zh: '知道', en: 'to know' }, { ru: 'зна́ние', zh: '知识', en: 'knowledge' }] },
          { ru: '-дум-', zh: '想', en: 'to think', examples: [{ ru: 'дума́ть', zh: '想', en: 'to think' }, { ru: 'дума', zh: '念头', en: 'thought' }] },
          { ru: '-люб-', zh: '爱', en: 'to love', examples: [{ ru: 'люби́ть', zh: '爱', en: 'to love' }, { ru: 'любо́вь', zh: '爱情', en: 'love' }] },
          { ru: '-сил-', zh: '力量', en: 'strength', examples: [{ ru: 'си́ла', zh: '力量', en: 'strength' }, { ru: 'си́льный', zh: '强壮的', en: 'strong' }] },
          { ru: '-добр-', zh: '善', en: 'good, kind', examples: [{ ru: 'добрый', zh: '善良的', en: 'kind' }, { ru: 'доброта́', zh: '善良', en: 'kindness' }] },
          { ru: '-чист-', zh: '清洁', en: 'clean', examples: [{ ru: 'чи́стый', zh: '干净的', en: 'clean' }, { ru: 'чистота́', zh: '清洁', en: 'cleanliness' }] },
        ],
      },
      {
        id: 'craft',
        title: { zh: '技艺与制度词根', en: 'Craft & system roots', ru: 'Корни ремесла и устройства' },
        items: [
          { ru: '-торг-', zh: '贸易', en: 'trade', examples: [{ ru: 'торг', zh: '买卖', en: 'trade' }, { ru: 'торго́вля', zh: '商业', en: 'commerce' }] },
          { ru: '-стр-', zh: '建造', en: 'to build', examples: [{ ru: 'стро́ить', zh: '建造', en: 'to build' }, { ru: 'строи́тель', zh: '建筑者', en: 'builder' }] },
          { ru: '-уч-', zh: '学习、教导', en: 'to teach, learn', examples: [{ ru: 'учи́ть', zh: '教/学', en: 'to teach/learn' }, { ru: 'уче́бник', zh: '教科书', en: 'textbook' }] },
          { ru: '-врач-', zh: '医生', en: 'doctor', examples: [{ ru: 'врач', zh: '医生', en: 'doctor' }, { ru: 'враче́бный', zh: '医疗的', en: 'medical' }] },
          { ru: '-прав-', zh: '正确、治理', en: 'right, rule', examples: [{ ru: 'пра́вильный', zh: '正确的', en: 'correct' }, { ru: 'правле́ние', zh: '管理', en: 'management' }] },
        ],
      },
    ],
  },

  // ───────── 主题词汇 ─────────
  {
    id: 'theme',
    title: { zh: '主题词汇', en: 'Thematic vocabulary', ru: 'Тематическая лексика' },
    groups: [
      {
        id: 'person-family',
        title: { zh: '人物与家庭', en: 'People & family', ru: 'Люди и семья' },
        items: [
          { ru: 'челове́к', zh: '人', en: 'person' },
          { ru: 'мужчи́на', zh: '男人', en: 'man' },
          { ru: 'же́нщина', zh: '女人', en: 'woman' },
          { ru: 'ребёнок', zh: '孩子', en: 'child' },
          { ru: 'ма́льчик', zh: '男孩', en: 'boy' },
          { ru: 'де́вочка', zh: '女孩', en: 'girl' },
          { ru: 'друг', zh: '朋友', en: 'friend' },
          { ru: 'подру́га', zh: '女友', en: 'female friend' },
          { ru: 'колле́га', zh: '同事', en: 'colleague' },
          { ru: 'сосе́д', zh: '邻居', en: 'neighbor' },
          { ru: 'семья́', zh: '家庭', en: 'family' },
          { ru: 'роди́тели', zh: '父母', en: 'parents' },
          { ru: 'оте́ц', zh: '父亲', en: 'father' },
          { ru: 'ма́ть', zh: '母亲', en: 'mother' },
          { ru: 'сын', zh: '儿子', en: 'son' },
        ],
      },
      {
        id: 'body-health',
        title: { zh: '身体与健康', en: 'Body & health', ru: 'Тело и здоровье' },
        items: [
          { ru: 'тело', zh: '身体', en: 'body' },
          { ru: 'голова́', zh: '头', en: 'head' },
          { ru: 'рука́', zh: '手/臂', en: 'hand/arm' },
          { ru: 'нога́', zh: '腿/脚', en: 'leg/foot' },
          { ru: 'глаз', zh: '眼睛', en: 'eye' },
          { ru: 'у́хо', zh: '耳朵', en: 'ear' },
          { ru: 'нос', zh: '鼻子', en: 'nose' },
          { ru: 'рот', zh: '嘴', en: 'mouth' },
          { ru: 'зуб', zh: '牙齿', en: 'tooth' },
          { ru: 'се́рдце', zh: '心脏', en: 'heart' },
          { ru: 'здоро́вье', zh: '健康', en: 'health' },
          { ru: 'боле́знь', zh: '疾病', en: 'illness' },
          { ru: 'врач', zh: '医生', en: 'doctor' },
          { ru: 'лека́рство', zh: '药', en: 'medicine' },
          { ru: 'боль', zh: '疼痛', en: 'pain' },
        ],
      },
      {
        id: 'nature-weather',
        title: { zh: '自然与天气', en: 'Nature & weather', ru: 'Природа и погода' },
        items: [
          { ru: 'приро́да', zh: '自然', en: 'nature' },
          { ru: 'пого́да', zh: '天气', en: 'weather' },
          { ru: 'со́лнце', zh: '太阳', en: 'sun' },
          { ru: 'не́бо', zh: '天空', en: 'sky' },
          { ru: 'земля́', zh: '土地', en: 'earth' },
          { ru: 'река́', zh: '河', en: 'river' },
          { ru: 'море', zh: '海', en: 'sea' },
          { ru: 'лес', zh: '森林', en: 'forest' },
          { ru: 'гора́', zh: '山', en: 'mountain' },
          { ru: 'дождь', zh: '雨', en: 'rain' },
          { ru: 'снег', zh: '雪', en: 'snow' },
          { ru: 'ве́тер', zh: '风', en: 'wind' },
          { ru: 'облако', zh: '云', en: 'cloud' },
          { ru: 'хо́лод', zh: '寒冷', en: 'cold' },
          { ru: 'тепло́', zh: '温暖', en: 'warmth' },
        ],
      },
      {
        id: 'time-date',
        title: { zh: '时间与日期', en: 'Time & dates', ru: 'Время и даты' },
        items: [
          { ru: 'вре́мя', zh: '时间', en: 'time' },
          { ru: 'час', zh: '小时', en: 'hour' },
          { ru: 'ми́нута', zh: '分钟', en: 'minute' },
          { ru: 'день', zh: '日/白天', en: 'day' },
          { ru: 'ночь', zh: '夜', en: 'night' },
          { ru: 'у́тро', zh: '早晨', en: 'morning' },
          { ru: 'ве́чер', zh: '晚上', en: 'evening' },
          { ru: 'неде́ля', zh: '周', en: 'week' },
          { ru: 'ме́сяц', zh: '月', en: 'month' },
          { ru: 'год', zh: '年', en: 'year' },
          { ru: 'весна́', zh: '春', en: 'spring' },
          { ru: 'ле́то', zh: '夏', en: 'summer' },
          { ru: 'о́сень', zh: '秋', en: 'autumn' },
          { ru: 'зи́ма', zh: '冬', en: 'winter' },
          { ru: 'сего́дня', zh: '今天', en: 'today' },
        ],
      },
      {
        id: 'color',
        title: { zh: '颜色', en: 'Colors', ru: 'Цвета' },
        items: [
          { ru: 'цвет', zh: '颜色', en: 'color' },
          { ru: 'кра́сный', zh: '红色的', en: 'red' },
          { ru: 'ора́нжевый', zh: '橙色的', en: 'orange' },
          { ru: 'жёлтый', zh: '黄色的', en: 'yellow' },
          { ru: 'зелёный', zh: '绿色的', en: 'green' },
          { ru: 'голубо́й', zh: '浅蓝色的', en: 'light blue' },
          { ru: 'си́ний', zh: '深蓝色的', en: 'dark blue' },
          { ru: 'фиоле́товый', zh: '紫色的', en: 'purple' },
          { ru: 'ро́зовый', zh: '粉红色的', en: 'pink' },
          { ru: 'ко́ричневый', zh: '棕色的', en: 'brown' },
          { ru: 'чёрный', zh: '黑色的', en: 'black' },
          { ru: 'бе́лый', zh: '白色的', en: 'white' },
          { ru: 'серый', zh: '灰色的', en: 'gray' },
          { ru: 'золотой', zh: '金色的', en: 'gold' },
          { ru: 'серебря́ный', zh: '银色的', en: 'silver' },
        ],
      },
      {
        id: 'animal',
        title: { zh: '动物', en: 'Animals', ru: 'Животные' },
        items: [
          { ru: 'живо́тное', zh: '动物', en: 'animal' },
          { ru: 'собака', zh: '狗', en: 'dog' },
          { ru: 'ко́шка', zh: '猫', en: 'cat' },
          { ru: 'лошадь', zh: '马', en: 'horse' },
          { ru: 'коро́ва', zh: '牛', en: 'cow' },
          { ru: 'свинья́', zh: '猪', en: 'pig' },
          { ru: 'овца́', zh: '羊', en: 'sheep' },
          { ru: 'курица', zh: '鸡', en: 'chicken' },
          { ru: 'птица', zh: '鸟', en: 'bird' },
          { ru: 'рыба', zh: '鱼', en: 'fish' },
          { ru: 'медве́дь', zh: '熊', en: 'bear' },
          { ru: 'волк', zh: '狼', en: 'wolf' },
          { ru: 'лиса́', zh: '狐狸', en: 'fox' },
          { ru: 'за́яц', zh: '兔子', en: 'hare' },
          { ru: 'мышь', zh: '老鼠', en: 'mouse' },
        ],
      },
      {
        id: 'food',
        title: { zh: '食物', en: 'Food', ru: 'Еда' },
        items: [
          { ru: 'еда́', zh: '食物', en: 'food' },
          { ru: 'хлеб', zh: '面包', en: 'bread' },
          { ru: 'молоко́', zh: '牛奶', en: 'milk' },
          { ru: 'мясо', zh: '肉', en: 'meat' },
          { ru: 'рыба', zh: '鱼', en: 'fish' },
          { ru: 'яйцо́', zh: '鸡蛋', en: 'egg' },
          { ru: 'суп', zh: '汤', en: 'soup' },
          { ru: 'ка́ша', zh: '粥', en: 'porridge' },
          { ru: 'овощ', zh: '蔬菜', en: 'vegetable' },
          { ru: 'фру́кт', zh: '水果', en: 'fruit' },
          { ru: 'яблоко', zh: '苹果', en: 'apple' },
          { ru: 'картофель', zh: '土豆', en: 'potato' },
          { ru: 'сахар', zh: '糖', en: 'sugar' },
          { ru: 'соль', zh: '盐', en: 'salt' },
          { ru: 'вода́', zh: '水', en: 'water' },
        ],
      },
      {
        id: 'clothing',
        title: { zh: '衣物', en: 'Clothing', ru: 'Одежда' },
        items: [
          { ru: 'оде́жда', zh: '衣服', en: 'clothing' },
          { ru: 'руба́шка', zh: '衬衫', en: 'shirt' },
          { ru: 'пла́тье', zh: '连衣裙', en: 'dress' },
          { ru: 'брюки', zh: '裤子', en: 'trousers' },
          { ru: 'ю́бка', zh: '裙子', en: 'skirt' },
          { ru: 'пальто́', zh: '大衣', en: 'coat' },
          { ru: 'ку́ртка', zh: '夹克', en: 'jacket' },
          { ru: 'о́бувь', zh: '鞋', en: 'shoes' },
          { ru: 'ша́пка', zh: '帽子', en: 'hat' },
          { ru: 'перча́тки', zh: '手套', en: 'gloves' },
          { ru: 'носки́', zh: '袜子', en: 'socks' },
          { ru: 'сви́тер', zh: '毛衣', en: 'sweater' },
          { ru: 'футбо́лка', zh: 'T恤', en: 't-shirt' },
          { ru: 'ремень', zh: '皮带', en: 'belt' },
          { ru: 'сумка', zh: '包', en: 'bag' },
        ],
      },
      {
        id: 'house',
        title: { zh: '房屋与家具', en: 'House & furniture', ru: 'Дом и мебель' },
        items: [
          { ru: 'дом', zh: '房子', en: 'house' },
          { ru: 'кварта́ра', zh: '公寓', en: 'apartment' },
          { ru: 'комна́та', zh: '房间', en: 'room' },
          { ru: 'ку́хня', zh: '厨房', en: 'kitchen' },
          { ru: 'ва́нная', zh: '浴室', en: 'bathroom' },
          { ru: 'туале́т', zh: '厕所', en: 'toilet' },
          { ru: 'дверь', zh: '门', en: 'door' },
          { ru: 'окно́', zh: '窗', en: 'window' },
          { ru: 'стол', zh: '桌子', en: 'table' },
          { ru: 'стул', zh: '椅子', en: 'chair' },
          { ru: 'дива́н', zh: '沙发', en: 'sofa' },
          { ru: 'крова́ть', zh: '床', en: 'bed' },
          { ru: 'шкаф', zh: '柜子', en: 'cupboard' },
          { ru: 'ла́мпа', zh: '灯', en: 'lamp' },
          { ru: 'стена́', zh: '墙', en: 'wall' },
        ],
      },
      {
        id: 'tools',
        title: { zh: '工具与器物', en: 'Tools & implements', ru: 'Инструменты' },
        items: [
          { ru: 'инструме́нт', zh: '工具', en: 'tool' },
          { ru: 'нож', zh: '刀', en: 'knife' },
          { ru: 'ло́жка', zh: '勺子', en: 'spoon' },
          { ru: 'ви́лка', zh: '叉子', en: 'fork' },
          { ru: 'тарелка', zh: '盘子', en: 'plate' },
          { ru: 'чашка', zh: '杯子', en: 'cup' },
          { ru: 'кни́га', zh: '书', en: 'book' },
          { ru: 'тетра́дь', zh: '本子', en: 'notebook' },
          { ru: 'ру́чка', zh: '笔', en: 'pen' },
          { ru: 'каранда́ш', zh: '铅笔', en: 'pencil' },
          { ru: 'моло́ток', zh: '锤子', en: 'hammer' },
          { ru: 'ключ', zh: '钥匙/扳手', en: 'key/wrench' },
          { ru: 'ножни́цы', zh: '剪刀', en: 'scissors' },
          { ru: 'телефо́н', zh: '电话', en: 'phone' },
          { ru: 'компью́тер', zh: '电脑', en: 'computer' },
        ],
      },
      {
        id: 'profession',
        title: { zh: '职业', en: 'Professions', ru: 'Профессии' },
        items: [
          { ru: 'профе́ссия', zh: '职业', en: 'profession' },
          { ru: 'учи́тель', zh: '教师', en: 'teacher' },
          { ru: 'врач', zh: '医生', en: 'doctor' },
          { ru: 'инжене́р', zh: '工程师', en: 'engineer' },
          { ru: 'студе́нт', zh: '学生', en: 'student' },
          { ru: 'рабо́чий', zh: '工人', en: 'worker' },
          { ru: 'продаве́ц', zh: '售货员', en: 'seller' },
          { ru: 'повар', zh: '厨师', en: 'cook' },
          { ru: 'води́тель', zh: '司机', en: 'driver' },
          { ru: 'юри́ст', zh: '律师', en: 'lawyer' },
          { ru: 'журнали́ст', zh: '记者', en: 'journalist' },
          { ru: 'эконо́мист', zh: '经济师', en: 'economist' },
          { ru: 'бухга́лтер', zh: '会计', en: 'accountant' },
          { ru: 'перево́дчик', zh: '翻译', en: 'translator' },
          { ru: 'программи́ст', zh: '程序员', en: 'programmer' },
        ],
      },
      {
        id: 'transport',
        title: { zh: '交通', en: 'Transport', ru: 'Транспорт' },
        items: [
          { ru: 'тра́нспорт', zh: '交通', en: 'transport' },
          { ru: 'маши́на', zh: '汽车', en: 'car' },
          { ru: 'авто́бус', zh: '公交车', en: 'bus' },
          { ru: 'тролле́йбус', zh: '无轨电车', en: 'trolleybus' },
          { ru: 'трамва́й', zh: '有轨电车', en: 'tram' },
          { ru: 'по́езд', zh: '火车', en: 'train' },
          { ru: 'самолёт', zh: '飞机', en: 'airplane' },
          { ru: 'корабль', zh: '船', en: 'ship' },
          { ru: 'велосипе́д', zh: '自行车', en: 'bicycle' },
          { ru: 'метро́', zh: '地铁', en: 'subway' },
          { ru: 'такси́', zh: '出租车', en: 'taxi' },
          { ru: 'билет', zh: '票', en: 'ticket' },
          { ru: 'ста́нция', zh: '车站', en: 'station' },
          { ru: 'остановка', zh: '停靠站', en: 'stop' },
          { ru: 'путь', zh: '道路', en: 'route' },
        ],
      },
      {
        id: 'school',
        title: { zh: '学校与学习', en: 'School & study', ru: 'Школа и учёба' },
        items: [
          { ru: 'шко́ла', zh: '学校', en: 'school' },
          { ru: 'университе́т', zh: '大学', en: 'university' },
          { ru: 'урок', zh: '课', en: 'lesson' },
          { ru: 'уче́бник', zh: '教科书', en: 'textbook' },
          { ru: 'тетра́дь', zh: '本子', en: 'notebook' },
          { ru: 'экза́мен', zh: '考试', en: 'exam' },
          { ru: 'оце́нка', zh: '成绩', en: 'grade' },
          { ru: 'учи́тель', zh: '老师', en: 'teacher' },
          { ru: 'учени́к', zh: '学生', en: 'pupil' },
          { ru: 'студе́нт', zh: '大学生', en: 'student' },
          { ru: 'зада́ние', zh: '作业', en: 'assignment' },
          { ru: 'уравне́ние', zh: '方程', en: 'equation' },
          { ru: 'форму́ла', zh: '公式', en: 'formula' },
          { ru: 'язы́к', zh: '语言', en: 'language' },
        ],
      },
      {
        id: 'emotion',
        title: { zh: '情感与心理', en: 'Emotions', ru: 'Эмоции' },
        items: [
          { ru: 'чувство', zh: '感觉', en: 'feeling' },
          { ru: 'ра́дость', zh: '喜悦', en: 'joy' },
          { ru: 'грусть', zh: '忧愁', en: 'sadness' },
          { ru: 'страх', zh: '恐惧', en: 'fear' },
          { ru: 'любо́вь', zh: '爱', en: 'love' },
          { ru: 'гнев', zh: '愤怒', en: 'anger' },
          { ru: 'удивле́ние', zh: '惊讶', en: 'surprise' },
          { ru: 'наде́жда', zh: '希望', en: 'hope' },
          { ru: 'за́висть', zh: '嫉妒', en: 'envy' },
          { ru: 'гордость', zh: '骄傲', en: 'pride' },
          { ru: 'оби́да', zh: '委屈', en: 'offense' },
          { ru: 'тоска́', zh: '思念', en: 'longing' },
          { ru: 'сча́стье', zh: '幸福', en: 'happiness' },
          { ru: 'весе́лье', zh: '欢乐', en: 'fun' },
          { ru: 'споко́йствие', zh: '平静', en: 'calm' },
        ],
      },
      {
        id: 'abstract',
        title: { zh: '抽象概念', en: 'Abstract concepts', ru: 'Абстрактные понятия' },
        items: [
          { ru: 'иде́я', zh: '想法', en: 'idea' },
          { ru: 'пробле́ма', zh: '问题', en: 'problem' },
          { ru: 'вопро́с', zh: '疑问', en: 'question' },
          { ru: 'отве́т', zh: '回答', en: 'answer' },
          { ru: 'причи́на', zh: '原因', en: 'reason' },
          { ru: 'це́ль', zh: '目标', en: 'goal' },
          { ru: 'смы́сл', zh: '意义', en: 'meaning' },
          { ru: 'факт', zh: '事实', en: 'fact' },
          { ru: 'те́ория', zh: '理论', en: 'theory' },
          { ru: 'ме́тод', zh: '方法', en: 'method' },
          { ru: 'результа́т', zh: '结果', en: 'result' },
          { ru: 'оши́бка', zh: '错误', en: 'mistake' },
          { ru: 'пра́вда', zh: '真相', en: 'truth' },
          { ru: 'ложь', zh: '谎言', en: 'lie' },
          { ru: 'свобо́да', zh: '自由', en: 'freedom' },
        ],
      },
    ],
  },

  // ───────── 功能词 ─────────
  {
    id: 'function',
    title: { zh: '功能词', en: 'Function words', ru: 'Служебные слова' },
    groups: [
      {
        id: 'preposition',
        title: { zh: '前置词', en: 'Prepositions', ru: 'Предлоги' },
        items: [
          { ru: 'в, во', zh: '在…里/到…里', en: 'in, into', note: '接第四格表示"到…里"，接第六格表示"在…里"（如 в шкафу́）' },
          { ru: 'на', zh: '在…上/到…上', en: 'on, onto', note: '接第四格表示"到…上"，接第六格表示"在…上"；某些场合也指"乘坐"（на авто́бусе）' },
          { ru: 'с, со', zh: '和…一起/从', en: 'with, from', note: '接第五格表示"和…一起"；接第二格表示"从…（表面/时间）"' },
          { ru: 'к, ко', zh: '向、对', en: 'to, toward', note: '接第三格，表示朝向某人或接近某时' },
          { ru: 'от, ото', zh: '从、离', en: 'from, away', note: '接第二格，表示离开某起点或情感来源' },
          { ru: 'до', zh: '到、直至', en: 'until, up to', note: '接第二格，表示时间/地点终点' },
          { ru: 'для', zh: '为了', en: 'for', note: '接第二格，表目的或受益对象' },
          { ru: 'из, ис', zh: '从…之中', en: 'out of, from', note: '接第二格，表从内部出来或出身来源' },
          { ru: 'у', zh: '在…旁/有', en: 'at, by', note: '接第二格，表处所"在…旁"或所属"…有"' },
          { ru: 'о, об, обо', zh: '关于', en: 'about, of', note: '接第六格，表"谈论/关于"' },
          { ru: 'по', zh: '沿/按/每逢', en: 'along, by', note: '接第三格表"沿着"；接第四格表"至（多处）"；复数第三格表"每逢"' },
          { ru: 'при', zh: '在…旁/附属于', en: 'at, attached to', note: '接第六格，表处所毗邻或附属于某机构' },
          { ru: 'без, бес', zh: '没有', en: 'without', note: '接第二格，表缺少' },
        ],
      },
      {
        id: 'conjunction',
        title: { zh: '连接词', en: 'Conjunctions', ru: 'Союзы' },
        items: [
          { ru: 'и', zh: '和、与', en: 'and', note: '并列连接词，连接等同成分' },
          { ru: 'а', zh: '而、则', en: 'and, whereas', note: '对比连接词，表对照"而…"' },
          { ru: 'но', zh: '但是', en: 'but', note: '转折连接词' },
          { ru: 'или', zh: '或', en: 'or', note: '选择连接词' },
          { ru: 'либо', zh: '或', en: 'either…or', note: '选择连接词，常成对"либо…либо…"' },
          { ru: 'что', zh: '什么/引导从句', en: 'that, what', note: '可作疑问代词"什么"；也可作连接词引导名词性或说明从句' },
          { ru: 'чтобы', zh: '为了、以便', en: 'in order to, so that', note: '引导目的或愿望从句，从句动词用过去时（除助词 бы 外）' },
          { ru: 'е́сли', zh: '如果', en: 'if', note: '条件连接词' },
          { ru: 'когда', zh: '当…时', en: 'when', note: '时间连接词' },
          { ru: 'пока', zh: '当…时/直到', en: 'while, until', note: '时间连接词；接否定时表"直到…才"' },
          { ru: 'как', zh: '怎样/作为', en: 'how, as', note: '疑问副词"如何"；连接词"作为、像"' },
          { ru: 'потому что', zh: '因为', en: 'because', note: '原因连接词，从句在后' },
          { ru: 'так как', zh: '既然、因为', en: 'since, as', note: '原因连接词，从句可在前或后' },
        ],
      },
      {
        id: 'particle',
        title: { zh: '粒词', en: 'Particles', ru: 'Частицы' },
        items: [
          { ru: 'не', zh: '不、没有', en: 'not', note: '否定粒词，与动词连用构成否定；与动词不定式连用表"别"（命令意味）' },
          { ru: 'ни', zh: '也不、任何也不', en: 'neither, not', note: '加强否定，常成对"ни…ни…（既不…也不…）"；也用于无人称句"нет = не + 有"' },
          { ru: 'же', zh: '则、就是', en: 'indeed, just', note: '强调粒词，表"正是、则"，置于被强调词后' },
          { ru: 'ли', zh: '是否', en: 'whether', note: '疑问粒词，置于句首词后，表一般疑问' },
          { ru: 'бы', zh: '（虚拟语气）', en: 'would (conditional)', note: '条件/愿望粒词，与过去时连用构成虚拟语气' },
          { ru: 'пусть', zh: '让、愿', en: 'let, may', note: '祈使粒词，表"让…吧"' },
          { ru: 'ведь', zh: '要知道', en: 'after all, you see', note: '提示粒词，表"要知道、本来"' },
          { ru: 'вот', zh: '这就是', en: 'here is, this is', note: '指示粒词，表"这就是、瞧"' },
          { ru: 'то́лько', zh: '只、仅', en: 'only', note: '限制粒词，表"仅仅"' },
          { ru: 'да́же', zh: '甚至', en: 'even', note: '强调粒词，表"甚至"' },
          { ru: 'и́менно', zh: '正是', en: 'exactly', note: '强调粒词，表"正是、就是"' },
          { ru: 'ра́зве', zh: '难道', en: 'really?', note: '疑问粒词，表"难道、莫非"' },
        ],
      },
      {
        id: 'interjection',
        title: { zh: '感叹词与拟声词', en: 'Interjections & onomatopoeia', ru: 'Междометия и звукоподражания' },
        items: [
          { ru: 'о', zh: '哦、啊', en: 'oh', note: '感叹，表惊奇或领悟' },
          { ru: 'ох', zh: '唉、哦', en: 'oh, ah', note: '感叹，表疲惫、遗憾或赞叹' },
          { ru: 'ах', zh: '啊', en: 'ah', note: '感叹，表惊喜、赞叹或懊恼' },
          { ru: 'увы', zh: '唉', en: 'alas', note: '感叹，表惋惜、遗憾' },
          { ru: 'ой', zh: '哎呀', en: 'ouch, oh', note: '感叹，表疼痛或惊呼' },
          { ru: 'эй', zh: '喂', en: 'hey', note: '招呼语，引起注意' },
          { ru: 'ну', zh: '嗯、那么', en: 'well, so', note: '语气词，表催促或停顿"那么、嗯"' },
          { ru: 'браво', zh: '好极了', en: 'bravo', note: '喝彩语，表赞赏' },
          { ru: 'ура́', zh: '乌拉', en: 'hurrah', note: '欢呼语，表胜利或喜悦' },
          { ru: 'стоп', zh: '停', en: 'stop', note: '叫停语' },
          { ru: 'мяу', zh: '喵', en: 'meow', note: '猫叫拟声' },
          { ru: 'гав', zh: '汪', en: 'woof', note: '狗叫拟声' },
        ],
      },
    ],
  },
]
